### ISSUE TITLE
Unplugging the keyboard crashes the program

### ISSUE THREAD

**Issue by wildtron** [Bornholm/node-keyboard#1]
hello, i'm currently using your module for my project. I'm getting an error when I unplug the keyboard and my this script crashes. I'm trying to catch every possible scenarios you see.. :D can you help me with this? thanks.. :D

**Comment by Bornholm** [comment]
Hi :)

You can handle the error like this:

```
k.on('error', function(err) {
 // Handle error
});
```

Your script will not crash but you'll have to recreate a new `Keyboard` object when replugging the keyboard.

I hope this will help you.

**Comment by wildtron** [comment]
@Bornholm Thank you very much! :D
